name: 'Deploy'
anthor: 'JetLu'
description: 'Github action for deploy website'
inputs:
  access_key:
    description: 'access key'
    required: true
  secret_key:
    description: 'secret key'
    required: true
  bucket:
    description: 'bucket'
    required: true
  source_dir:
    description: 'source dir'
    default: './'
    required: false
  dest_dir:
    description: 'dest dir, namely key prefix'
    default: '/'
    required: false
  ignore_source_map:
    description: 'ignore source maps'
    default: true
    required: false

runs:
  using: 'node16'
  main: 'index.mjs'
