name: 'Deploy'
anthor: 'JetLu'
description: 'Github action for deploy website'
inputs:
  ACCESS_KEY:
    description: 'Qiniu Access Key'
    required: true
  SECRET_KEY:
    description: 'Qiniu Secret Key'
    required: true
  BUCKET:
    description: 'Qiniu Bucket'
    required: true
  SOURCE_DIR:
    description: 'Local Dir'
    default: './'
    required: false
  DEST_DIR:
    description: 'Qiniu Prefix'
    default: '/'
    required: false
  SSH_KEY:
    description: 'SSH Key'
    required: false
  SSH_HOST:
    description: 'SSH Host'
    required: false
  SSH_PORT:
    description: 'SSH Port'

runs:
  using: 'node16'
  main: 'dist/index.mjs'
