name: 'Deploy'
anthor: 'JetLu'
description: 'Github action for deploy website'
inputs:
  access_key:
    description: 'access key'
    required: true
  secret_key:
    description: 'secret key'
    required: true
  bucket:
    description: 'bucket'
    required: true
  source_dir:
    description: 'source dir'
    default: './'
    required: false
  dest_dir:
    description: 'dest dir, namely key prefix'
    default: '/'
    required: false

outputs:
  files:
    description: '多少文件'

runs:
  using: 'node16'
  main: 'dist/index.mjs'
